version: "3.9"
services:
  cookies-extractor:
    build:
      context: ../..
      dockerfile: deploy/docker/cookies-extractor/Dockerfile
    environment:
      COOKIES_BROWSER: firefox
      COOKIES_BROWSER_PROFILE: /cookies_extractor/firefox_profile
      COOKIES_DOMAIN: youtube.com
      COOKIES_OUTPUT_DIR: /cookies_extractor/cookies/YouTube
      COOKIES_OUTPUT_FILE: www.youtube.com_cookies.txt
      COOKIES_MIN_COOKIES: 1
    volumes:
      - ${HOME}/cookies:/cookies_extractor/cookies:rw
      - ${HOME}/firefox_profile:/cookies_extractor/firefox_profile:ro
    restart: "no"
